kind: Pod
apiVersion: v1
metadata:
  name: web-server-{{.Replica}}
  labels:
    app: web-server-{{.Replica}}
    group: kb-mb-wl
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  containers:
  - name: nginx
    image: {{ .containerImage }}
    ports:
    imagePullPolicy: IfNotPresent
  securityContext:
    privileged: true
    sysctls:
    - name: net.ipv4.ip_local_port_range
      value: "1024 65535"
    - name: net.ipv4.tcp_tw_reuse
      value: "1"
    - name: net.netfilter.nf_conntrack_tcp_timeout_time_wait
      value: "1"
