apiVersion: v1
kind: Service
metadata:
  labels:
    app: http-{{.Replica}}
    group: kb-mb-wl
  name: web-service-{{.Replica}}
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: web-server-{{.Replica}}
  type: NodePort

